ROOT_DIR = $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
PIPY_DIR = $(abspath ${ROOT_DIR}/../../..)

BIN_DIR = $(ROOT_DIR)
INC_DIR = $(abspath ${PIPY_DIR}/include) -I$(abspath ${PIPY_DIR}/src) -I/usr/include/mysql

PRODUCT = ${BIN_DIR}/mysql-nmi.so

CXXFLAGS = -std=c++11 -fPIC
LDFLAGS = -L/usr/lib/x86_64-linux-gnu -l mysqlclient -lssl -lcrypto -lpthread -lstdc++ -ldl -fPIC -shared

OS = $(shell uname -s)

ifeq (${OS},Darwin)
  LDFLAGS = -Wl,-flat_namespace,-undefined,dynamic_lookup
endif

all: ${PRODUCT} 

${PRODUCT}: ${ROOT_DIR}/mysql.c
	clang -I${INC_DIR} ${LDFLAGS} $< -o $@

clean:
	rm -f ${PRODUCT} 

test:
	${BIN_DIR}/pipy main.js --threads=max --reuse-port
